### ISSUE TITLE
testnet version of script.sh displays mainnet script message when invoked with github_pull

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go-scripts-testnet#2]
I am following instructions to prepare for Public Testnet T1.1.0.1.  I invoke script.sh from elrond-go-scripts-testnet directory with command github_pull.   As you can see in the following output, the script displays a confirmation that **elrond-go-scripts-mainnet is reachable.** 

elrond@ubuntu-16gb-nbg1-1:~/elrond-go-scripts-testnet$ bash script.sh github_pull

Backing up your current custom variables...

Your current saved varaibles are:

CUSTOM_HOME="/home/elrond"
CUSTOM_USER="elrond"
NODE_KEYS_LOCATION="$CUSTOM_HOME/VALIDATOR_KEYS"
GITHUBTOKEN=""
IDENTITY=""
NODE_EXTRA_FLAGS=""

---> Fetching the latest version of the sripts...

**---> elrond-go-scripts-mainnet is reachable ! Pulling latest version...**
HEAD is now at c5ee534 configs repo fix
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8 (delta 5), reused 6 (delta 3), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/ElrondNetwork/elrond-go-scripts-testnet
   c5ee534..81de8de  master     -> origin/master
Updating c5ee534..81de8de
Fast-forward
 config/variables.cfg |  4 ++--
 script.sh            | 10 +++++-----
 2 files changed, 7 insertions(+), 7 deletions(-)
---> Restoring your config files

---> Restoring your config files

---> Finished fetching scripts...

elrond

**Comment by valentin-lup** [comment]
This has been fixed. Thank you for pointing it out.
